### ISSUE TITLE
Not setting up. Maybe an issue of my setup

### ISSUE THREAD

**Issue by alnavasa** [clyra/unifics#14]
This is the error I get:

<img width="474" alt="Captura de pantalla 2021-12-17 a las 0 07 27" src="https://user-images.githubusercontent.com/458370/146462241-e42da30d-0692-4e9d-9b8d-aebaeabb2b16.png">

This is my config:

```
# SENSOR
sensor:



  - platform: unifigateway
    host: !secret unifi.host 
    username: !secret unifi.username
    password: !secret unifi.password
    port: 8443



  - platform: unifics
    name: unifics
    host: !secret unifi.host 
    port: 8443
    username: !secret unifi.username
    password: !secret unifi.password
```

unifigateway sensor is working, but not unifics
