### ISSUE TITLE
Specify a wifi network to show clients 

### ISSUE THREAD

**Issue by veeds2** [clyra/unifics#32]
Problem: There is currently no way to select the wifi network from which to display connected clients. 

Unifi APs can broadcast multiple wifi SSIDs. For Example the Chime being assigned to "Unifi Wireless". Is there some way to select the wifi network name at initial configuration so that all other clients connected to the AP but sit on a different wifi network are ignored?

Thank you

**Comment by clyra** [comment]
Hi,

The sensor shows the number of clients per ssid and per Access Points as attributes. You may display all of them with a entity-attribute card, for example:

````
entities:
  - sensor.unifi
  - entity: sensor.unifi
    filter:
      include:
        - sensor.unifi.<ssid foo>
        - sensor.unifi.<ssid bar>
        - sensor.unifi.<ssid guest>
        - key: sensor.unifi.ap*
    heading_name: Attributes
    heading_state: States
    type: custom:entity-attributes-card
title: Unifi
type: entities
````

Another option is just create a template sensor and use something like "{{ state_attr('sensor.unifi', '<your ssid>') }} as the "value_template".
